/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "#000666",
        "primary-container": "#1a237e",
        "on-primary": "#ffffff",
        "on-primary-container": "#8690ee",
        "primary-fixed": "#e0e0ff",
        "primary-fixed-dim": "#bdc2ff",
        secondary: "#9f4200",
        "secondary-container": "#fd6c00",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#562000",
        "secondary-fixed": "#ffdbcb",
        "secondary-fixed-dim": "#ffb692",
        "on-secondary-fixed": "#341100",
        tertiary: "#002103",
        "tertiary-container": "#003909",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#a3f69c",
        "tertiary-fixed-dim": "#88d982",
        "on-tertiary-fixed": "#002204",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        background: "#f8f9fb",
        surface: "#f8f9fb",
        "surface-dim": "#d8dadc",
        "surface-bright": "#f8f9fb",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "surface-container": "#eceef0",
        "surface-container-high": "#e6e8ea",
        "surface-container-highest": "#e0e3e5",
        "on-surface": "#191c1e",
        "on-surface-variant": "#454652",
        outline: "#767683",
        "outline-variant": "#c6c5d4",
        "inverse-surface": "#2d3133",
        "inverse-on-surface": "#eff1f3",
        "inverse-primary": "#bdc2ff",
        "surface-tint": "#4c56af",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm: "0.375rem",
        lg: "0.75rem",
        xl: "1rem",
        "2xl": "1.25rem",
        full: "9999px",
      },
      boxShadow: {
        editorial: "0 24px 48px -12px rgba(0,6,102,0.08)",
        "editorial-sm": "0 8px 24px -4px rgba(0,6,102,0.06)",
        glass: "0 4px 24px rgba(0,6,102,0.06)",
      },
      keyframes: {
        fadeUp: {
          "0%": { opacity: "0", transform: "translateY(14px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        slideIn: {
          "0%": { opacity: "0", transform: "translateX(20px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-400px 0" },
          "100%": { backgroundPosition: "400px 0" },
        },
      },
      animation: {
        "fade-up": "fadeUp 0.35s ease forwards",
        "slide-in": "slideIn 0.3s ease forwards",
        shimmer: "shimmer 1.4s infinite linear",
      },
    },
  },
  plugins: [],
};
